version: '3'

services:
  devfun.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  devfun.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
